### ISSUE TITLE
For ξεναγέω short def. problem (using Middle Liddell)

### ISSUE THREAD

**Issue by demophobos** [alpheios-project/ml#3]
![ξεναγέω](https://user-images.githubusercontent.com/7735754/102404864-57f4ce00-3ff9-11eb-9c8b-153dc75663f1.png)

**Comment by monzug** [comment]
ἐξενάγηται has been fixed in Middle Liddell

![Screen Shot 2021-01-14 at 2 22 34 PM](https://user-images.githubusercontent.com/41396793/104596466-4cd2a380-5674-11eb-80f5-534a38ce365f.png)

I did also check the other dictionaries (no definition found in Homeric Lexicon, dodson, Abbott-Smith, the others are ok)
